spring:
  application:
    name: notification-service

  data:
    redis:
      host: ${HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

logging:
  level:
    com.github.seecret1: DEBUG

server:
  port: 8082

app:
  redis:
    stream:
      key: orders
      pollTimeout: 500ms
      countRetry: 3
      retrying: 10m
      max-batch-size: 50
      value-limited: 100
      consumer-group: notification-group
      consumer-name: notification-service-1